### ISSUE TITLE
weird app opening issue on android 14

### ISSUE THREAD

**Issue by stlineo** [reiryuki/One-UI-Home-34-Magisk-Module#1]
when i try to open an app the launcher makes the app go blank and even crashes the launcher sometimes. heres a video of what happens if i try to open an app

https://github.com/reiryuki/One-UI-Home-34-Magisk-Module/assets/115903934/67f6e121-34a7-44fd-9977-49c675236f5d

**Comment by reiryuki** [comment]
-------------- Any missing stuffs --------------
------------- will not be approved -------------

Bug report contains 6 stuffs:

1) Explanations ✓
2) Magisk/KernelSU install log if it's a Magisk module #magisk_install_log
3) Disable any other else modules (except the module you want to report, AML, dirac misoundfx Remover, AOSP soundfx Remover, & Sound Alive FX Remover Magisk Module. But if you are reporting for AML Ryuki Mod, then you need to enable all audio mod module you have.)
4) Full logcat #logcat
5) Z folder #zfolder
6) Screenshot all super user lists for KSU users

If you miss one of them, read #bug_report again https://t.me/androidryukimodsdiscussions/2618 please! If you got boot-loop, read #workarounds! If you don't understand, learning is the best you can do. Thank you.
